version: '3'

services: 
    redis:
        image: redis:alpine
    back: 
        image: 'backend'
        ports:
         - 8000:8000
        environment:
         - REDIS=redis
    front: 
        image: 'frontend'
        ports:
         - 5000:5000
