version: '3.5'

services: 
    postgres:
        image: postgres:alpine
        environment:
         - POSTGRES_PASSWORD=example
    redis:
        image: redis:alpine
    backend: 
        image: 'backend'
        environment:
         - REDIS=redis
         - DB_HOST=postgres
         - DB_USERNAME=postgres
         - DB_PASSWORD=example
        ports:
         - 8000:8000
    frontend: 
        image: 'frontend'
        environment:
         - API_URL=http://localhost/api
        ports:
         - 5000:5000
    nginx:
        image: nginx:alpine
        volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
         - 80:80
